### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by DrDinosaur** [lgandx/Responder-Windows#1]
Was this made, at least in part, in response to this: https://github.com/SpiderLabs/Responder/issues/37

**Comment by lgandx** [comment]
No. Please read the readme file for this version please if you want to know the purpose of this version.

**Comment by DrDinosaur** [comment]
"Goal of this version is to be able to propagate compromises across subnets and domains from any compromised Windows machine. This tool can also be used compromise a domain from an external penetration test." That was the main thing mentioned and it looks like this tool has it?
