### ISSUE TITLE
Set IP to redirect to

### ISSUE THREAD

**Issue by vysec** [lgandx/Responder-Windows#2]
Hi, I think some changes in ICMP-redirect.py broke my original fix to the SpiderLabs repo.

Basically I made:

python Responder.py -I eth0 -wF -i 8.8.8.8

Poison requests to give a value of 8.8.8.8 and it would launch 445 on all interfaces. Currently there is no longer a way to redirect to another IP...

**Comment by lgandx** [comment]
This repo is for the Responder Windows version, you probably meant: https://github.com/lgandx/Responder
